In [99]:
# importing necessary libraries : 

import pandas as pd 
import numpy as np 
import seaborn as sns 
import matplotlib.pyplot as plt
%matplotlib inline

In [100]:
# importing the dataset :
df=pd.read_excel('Data_file.xlsx',header=1)

In [101]:
df.head(2)

Unnamed: 0 Unnamed: 1 Unnamed: 2 Unnamed: 3    Unnamed: 4  \
0      S.No.    College       Role  City type  Previous CTC   
1          1     Tier 1    Manager  Non-Metro         55523   

             Unnamed: 5        Unnamed: 6    Unnamed: 7    Unnamed: 8  
0  Previous job changes  Graduation marks  Exp (Months)           CTC  
1                     3                66            19  71406.576531

### Data Preprocessing :

In [102]:
df.columns=df.iloc[0]

In [103]:
df.head(2)

0  S.No.  College     Role  City type  Previous CTC  Previous job changes  \
0  S.No.  College     Role  City type  Previous CTC  Previous job changes   
1      1   Tier 1  Manager  Non-Metro         55523                     3   

0  Graduation marks  Exp (Months)           CTC  
0  Graduation marks  Exp (Months)           CTC  
1                66            19  71406.576531

In [104]:
df=df.drop(index=0,columns='S.No.')

In [105]:
df.head(5)

0 College       Role  City type Previous CTC Previous job changes  \
1  Tier 1    Manager  Non-Metro        55523                    3   
2  Tier 2  Executive      Metro        57081                    1   
3  Tier 2  Executive      Metro        60347                    2   
4  Tier 3  Executive      Metro        49010                    2   
5  Tier 3  Executive      Metro        57879                    4   

0 Graduation marks Exp (Months)           CTC  
1               66           19  71406.576531  
2               84           18  68005.870631  
3               52           28  76764.020277  
4               81           33   82092.38688  
5               74           32  73878.097729

In [106]:
df.shape

(1338, 8)

In [107]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1338 entries, 1 to 1338
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype 
---  ------                --------------  ----- 
 0   College               1338 non-null   object
 1   Role                  1338 non-null   object
 2   City type             1338 non-null   object
 3   Previous CTC          1338 non-null   object
 4   Previous job changes  1338 non-null   object
 5   Graduation marks      1338 non-null   object
 6   Exp (Months)          1338 non-null   object
 7   CTC                   1338 non-null   object
dtypes: object(8)
memory usage: 94.1+ KB


In [108]:
cols=['Previous CTC','Previous job changes','Graduation marks','Exp (Months)','CTC']
for col in cols:
    df[col]=df[col].astype(int)

In [109]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1338 entries, 1 to 1338
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype 
---  ------                --------------  ----- 
 0   College               1338 non-null   object
 1   Role                  1338 non-null   object
 2   City type             1338 non-null   object
 3   Previous CTC          1338 non-null   int32 
 4   Previous job changes  1338 non-null   int32 
 5   Graduation marks      1338 non-null   int32 
 6   Exp (Months)          1338 non-null   int32 
 7   CTC                   1338 non-null   int32 
dtypes: int32(5), object(3)
memory usage: 67.9+ KB


In [110]:
df.isnull().sum()

0
College                 0
Role                    0
City type               0
Previous CTC            0
Previous job changes    0
Graduation marks        0
Exp (Months)            0
CTC                     0
dtype: int64

--> No null values.

In [111]:
# Seperating categorical and numerical variables:
cat_col=['College','Role','City type']
num_col=[col for col in df.columns.to_list() if col not in cat_col]

In [112]:
print(f'numerical columns are : {num_col}')
print(f'categorical variables are : {cat_col}')

numerical columns are : ['Previous CTC', 'Previous job changes', 'Graduation marks', 'Exp (Months)', 'CTC']
categorical variables are : ['College', 'Role', 'City type']


In [113]:
df.describe()

0      Previous CTC  Previous job changes  Graduation marks  Exp (Months)  \
count   1338.000000           1338.000000       1338.000000   1338.000000   
mean   55581.762332              2.525411         59.890882     39.207025   
std     6685.600553              1.123502         14.894696     14.049960   
min    36990.000000              1.000000         35.000000     18.000000   
25%    50547.000000              2.000000         47.000000     27.000000   
50%    55293.500000              3.000000         60.000000     39.000000   
75%    60150.500000              4.000000         73.000000     51.000000   
max    77911.000000              4.000000         85.000000     64.000000   

0                CTC  
count    1338.000000  
mean    75458.846786  
std     12551.284470  
min     53020.000000  
25%     66904.750000  
50%     73112.500000  
75%     80746.500000  
max    123416.000000

### Model training

In [114]:
df=pd.get_dummies(df)

In [115]:
y=df['CTC']

In [116]:
X=df.drop(columns='CTC')

In [117]:
y.shape, X.shape

((1338,), (1338, 11))

In [118]:

from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()

In [119]:
X_scaled=scaler.fit_transform(X)

In [120]:
X_scaled

array([[-0.00879267,  0.42257741,  0.4103073 , ...,  1.97058663,
        -1.0105187 ,  1.0105187 ],
       [ 0.22433261, -1.35823699,  1.61924306, ..., -0.5074631 ,
         0.98959079, -0.98959079],
       [ 0.71302785, -0.46782979, -0.52997607, ..., -0.5074631 ,
         0.98959079, -0.98959079],
       ...,
       [ 0.95393396, -1.35823699, -0.86579156, ..., -0.5074631 ,
        -1.0105187 ,  1.0105187 ],
       [-0.35593687,  0.42257741,  0.61179659, ..., -0.5074631 ,
        -1.0105187 ,  1.0105187 ],
       [-0.56287671, -1.35823699, -0.86579156, ...,  1.97058663,
        -1.0105187 ,  1.0105187 ]])

In [121]:
y

1       71406
2       68005
3       76764
4       82092
5       73878
        ...  
1334    69712
1335    69298
1336    66397
1337    64044
1338    83346
Name: CTC, Length: 1338, dtype: int32

In [122]:
from sklearn.model_selection import train_test_split

In [123]:
X_train,X_test,y_train, y_test=train_test_split(X,y,test_size=0.3,random_state=0)

In [124]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()

In [125]:
lr.fit(X_scaled,y)

LinearRegression()

In [126]:
# import test data : 
df_test=pd.read_excel('Test_data_file.xlsx')

In [127]:
df_test.head(4)

College       Role  City type  College_T1  College_T2  Role_Manager  \
0  Tier 1    Manager  Non-Metro           1           0             1   
1  Tier 2  Executive      Metro           0           1             0   
2  Tier 2  Executive      Metro           0           1             0   
3  Tier 3  Executive      Metro           0           0             0   

   City_Metro  previous CTC  previous job changes  Graduation marks  ...  \
0           0         55523                     3                66  ...   
1           1         57081                     1                84  ...   
2           1         60347                     2                52  ...   
3           1         49010                     2                81  ...   

   Unnamed: 14   Unnamed: 15  Unnamed: 16  Unnamed: 17   Unnamed: 18  \
0          NaN           NaN          NaN          NaN           NaN   
1          NaN  32438.761916  4659.731658  -832.274662  19359.943901   
2          NaN           NaN          NaN          NaN           NaN   
3          NaN           NaN          NaN          NaN           NaN   

   Unnamed: 19  Unnamed: 20  Unnamed: 21  Unnamed: 22  Unnamed: 23  
0          NaN          NaN          NaN          NaN          NaN  
1  4080.577268     0.451593   -29.041071     -3.65235   258.940639  
2          NaN          NaN          NaN          NaN          NaN  
3          NaN          NaN          NaN          NaN          NaN  

[4 rows x 24 columns]

In [128]:
df_test.shape

(1338, 24)

In [129]:
df_test=df_test.drop(columns=['College_T1','College_T2','Role_Manager','City_Metro','Predicted CTC','Unnamed: 13','Unnamed: 14','Unnamed: 15','Unnamed: 16','Unnamed: 17','Unnamed: 18','Unnamed: 19','Unnamed: 20','Unnamed: 21','Unnamed: 22','Unnamed: 23',])

In [130]:
df_test.shape

(1338, 8)

In [131]:
df_test.head(5)

College       Role  City type  previous CTC  previous job changes  \
0  Tier 1    Manager  Non-Metro         55523                     3   
1  Tier 2  Executive      Metro         57081                     1   
2  Tier 2  Executive      Metro         60347                     2   
3  Tier 3  Executive      Metro         49010                     2   
4  Tier 3  Executive      Metro         57879                     4   

   Graduation marks  Exp    Actual CTC  
0                66   19  71406.576531  
1                84   18  68005.870631  
2                52   28  76764.020277  
3                81   33  82092.386880  
4                74   32  73878.097729

In [132]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   College               1338 non-null   object 
 1   Role                  1338 non-null   object 
 2   City type             1338 non-null   object 
 3   previous CTC          1338 non-null   int64  
 4   previous job changes  1338 non-null   int64  
 5   Graduation marks      1338 non-null   int64  
 6   Exp                   1338 non-null   int64  
 7   Actual CTC            1338 non-null   float64
dtypes: float64(1), int64(4), object(3)
memory usage: 83.8+ KB


In [133]:
act_ctc=df_test['Actual CTC']

In [134]:
X_test=df_test.drop(columns='Actual CTC')

In [135]:
X_test=pd.get_dummies(X_test)

In [136]:
X_test_scaled=scaler.fit_transform(X_test)

In [137]:
X_test_scaled

array([[-0.00879267,  0.42257741,  0.4103073 , ...,  1.97058663,
        -1.0105187 ,  1.0105187 ],
       [ 0.22433261, -1.35823699,  1.61924306, ..., -0.5074631 ,
         0.98959079, -0.98959079],
       [ 0.71302785, -0.46782979, -0.52997607, ..., -0.5074631 ,
         0.98959079, -0.98959079],
       ...,
       [ 0.95393396, -1.35823699, -0.86579156, ..., -0.5074631 ,
        -1.0105187 ,  1.0105187 ],
       [-0.35593687,  0.42257741,  0.61179659, ..., -0.5074631 ,
        -1.0105187 ,  1.0105187 ],
       [-0.56287671, -1.35823699, -0.86579156, ...,  1.97058663,
        -1.0105187 ,  1.0105187 ]])

In [138]:
Predicted_CTC=lr.predict(X_test_scaled)

In [139]:
Predicted_CTC

array([86123.40298499, 65789.03022489, 69941.17971119, ...,
       64045.53709694, 66222.7165806 , 90794.45437238])

In [140]:
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error

In [141]:
score=r2_score(y,Predicted_CTC)

In [142]:
# R2 Score:
score

0.6081866290468363

In [143]:
mean_absolute_error(y,Predicted_CTC)

6159.182836706974

In [144]:
mean_squared_error(y,Predicted_CTC)

61678086.54262962